import AsyncStorage from '@react-native-async-storage/async-storage';

export type ThemeId = 'classic' | 'vintage' | 'cinema' | 'neon' | 'ocean' | 'forest' | 'sunset' | 'midnight' | 'rose' | 'monochrome' | 'galaxy' | 'sakura' | 'nord' | 'dracula' | 'monokai' | 'solarized' | 'matrix';

export interface ThemeColors {
    background: string;
    surface: string;
    surfaceLight: string;
    primary: string;
    primaryGradientFrom: string;
    primaryGradientTo: string;
    accent: string;
    textPrimary: string;
    textSecondary: string;
    textMuted: string;
    border: string;
}

export interface Theme {
    id: ThemeId;
    name: string;
    colors: {
        light: ThemeColors;
        dark: ThemeColors;
    };
}

export const themes: Record<ThemeId, Theme> = {
    classic: {
        id: 'classic',
        name: 'Klasik',
        colors: {
            light: {
                background: '#fafafa',
                surface: '#ffffff',
                surfaceLight: '#f4f4f5',
                primary: '#18181b',
                primaryGradientFrom: '#27272a',
                primaryGradientTo: '#3f3f46',
                accent: '#52525b',
                textPrimary: '#09090b',
                textSecondary: '#3f3f46',
                textMuted: '#a1a1aa',
                border: '#e4e4e7',
            },
            dark: {
                background: '#09090b',
                surface: '#18181b',
                surfaceLight: '#27272a',
                primary: '#fafafa',
                primaryGradientFrom: '#e4e4e7',
                primaryGradientTo: '#d4d4d8',
                accent: '#a1a1aa',
                textPrimary: '#fafafa',
                textSecondary: '#d4d4d8',
                textMuted: '#52525b',
                border: '#27272a',
            },
        },
    },
    vintage: {
        id: 'vintage',
        name: 'Vintage',
        colors: {
            light: {
                background: '#fdf6e3',
                surface: '#fefcf6',
                surfaceLight: '#f5eed6',
                primary: '#b45309',
                primaryGradientFrom: '#b45309',
                primaryGradientTo: '#92400e',
                accent: '#854d0e',
                textPrimary: '#422006',
                textSecondary: '#78716c',
                textMuted: '#a8a29e',
                border: '#d6d3d1',
            },
            dark: {
                background: '#1c1917',
                surface: '#292524',
                surfaceLight: '#44403c',
                primary: '#d97706',
                primaryGradientFrom: '#d97706',
                primaryGradientTo: '#b45309',
                accent: '#fbbf24',
                textPrimary: '#fef3c7',
                textSecondary: '#a8a29e',
                textMuted: '#78716c',
                border: '#44403c',
            },
        },
    },
    cinema: {
        id: 'cinema',
        name: 'Sinema',
        colors: {
            light: {
                background: '#f5f5f4',
                surface: '#fafaf9',
                surfaceLight: '#e7e5e4',
                primary: '#b45309',
                primaryGradientFrom: '#ca8a04',
                primaryGradientTo: '#b45309',
                accent: '#eab308',
                textPrimary: '#1c1917',
                textSecondary: '#57534e',
                textMuted: '#78716c',
                border: '#d6d3d1',
            },
            dark: {
                background: '#09090b',
                surface: '#18181b',
                surfaceLight: '#27272a',
                primary: '#eab308',
                primaryGradientFrom: '#facc15',
                primaryGradientTo: '#ca8a04',
                accent: '#fde047',
                textPrimary: '#fafafa',
                textSecondary: '#a1a1aa',
                textMuted: '#71717a',
                border: '#27272a',
            },
        },
    },
    neon: {
        id: 'neon',
        name: 'Neon',
        colors: {
            light: {
                background: '#fdf4ff',
                surface: '#fefefe',
                surfaceLight: '#fae8ff',
                primary: '#d946ef',
                primaryGradientFrom: '#d946ef',
                primaryGradientTo: '#06b6d4',
                accent: '#22d3ee',
                textPrimary: '#1e1b4b',
                textSecondary: '#6b21a8',
                textMuted: '#a855f7',
                border: '#e879f9',
            },
            dark: {
                background: '#0c0a1d',
                surface: '#140f2d',
                surfaceLight: '#1e1847',
                primary: '#e879f9',
                primaryGradientFrom: '#d946ef',
                primaryGradientTo: '#06b6d4',
                accent: '#22d3ee',
                textPrimary: '#f0abfc',
                textSecondary: '#c084fc',
                textMuted: '#7c3aed',
                border: '#3b0764',
            },
        },
    },
    ocean: {
        id: 'ocean',
        name: 'Okyanus',
        colors: {
            light: {
                background: '#f0f9ff',
                surface: '#ffffff',
                surfaceLight: '#e0f2fe',
                primary: '#0284c7',
                primaryGradientFrom: '#0284c7',
                primaryGradientTo: '#0891b2',
                accent: '#06b6d4',
                textPrimary: '#0c4a6e',
                textSecondary: '#0369a1',
                textMuted: '#7dd3fc',
                border: '#bae6fd',
            },
            dark: {
                background: '#0c1929',
                surface: '#0f2942',
                surfaceLight: '#1a3a57',
                primary: '#38bdf8',
                primaryGradientFrom: '#0ea5e9',
                primaryGradientTo: '#22d3ee',
                accent: '#22d3ee',
                textPrimary: '#e0f2fe',
                textSecondary: '#7dd3fc',
                textMuted: '#0369a1',
                border: '#0c4a6e',
            },
        },
    },
    forest: {
        id: 'forest',
        name: 'Orman',
        colors: {
            light: {
                background: '#f0fdf4',
                surface: '#ffffff',
                surfaceLight: '#dcfce7',
                primary: '#16a34a',
                primaryGradientFrom: '#16a34a',
                primaryGradientTo: '#059669',
                accent: '#10b981',
                textPrimary: '#14532d',
                textSecondary: '#166534',
                textMuted: '#86efac',
                border: '#bbf7d0',
            },
            dark: {
                background: '#0a1f0d',
                surface: '#132f15',
                surfaceLight: '#1a4220',
                primary: '#4ade80',
                primaryGradientFrom: '#22c55e',
                primaryGradientTo: '#34d399',
                accent: '#34d399',
                textPrimary: '#dcfce7',
                textSecondary: '#86efac',
                textMuted: '#166534',
                border: '#14532d',
            },
        },
    },
    sunset: {
        id: 'sunset',
        name: 'Günbatımı',
        colors: {
            light: {
                background: '#fff7ed',
                surface: '#ffffff',
                surfaceLight: '#ffedd5',
                primary: '#ea580c',
                primaryGradientFrom: '#ea580c',
                primaryGradientTo: '#e11d48',
                accent: '#f43f5e',
                textPrimary: '#7c2d12',
                textSecondary: '#c2410c',
                textMuted: '#fdba74',
                border: '#fed7aa',
            },
            dark: {
                background: '#1c0c05',
                surface: '#2d1810',
                surfaceLight: '#44241a',
                primary: '#fb923c',
                primaryGradientFrom: '#f97316',
                primaryGradientTo: '#fb7185',
                accent: '#fb7185',
                textPrimary: '#ffedd5',
                textSecondary: '#fdba74',
                textMuted: '#c2410c',
                border: '#7c2d12',
            },
        },
    },
    midnight: {
        id: 'midnight',
        name: 'Gece',
        colors: {
            light: {
                background: '#f5f3ff',
                surface: '#ffffff',
                surfaceLight: '#ede9fe',
                primary: '#7c3aed',
                primaryGradientFrom: '#7c3aed',
                primaryGradientTo: '#4f46e5',
                accent: '#6366f1',
                textPrimary: '#2e1065',
                textSecondary: '#5b21b6',
                textMuted: '#c4b5fd',
                border: '#ddd6fe',
            },
            dark: {
                background: '#0a0520',
                surface: '#120a30',
                surfaceLight: '#1e1045',
                primary: '#a78bfa',
                primaryGradientFrom: '#8b5cf6',
                primaryGradientTo: '#818cf8',
                accent: '#818cf8',
                textPrimary: '#ede9fe',
                textSecondary: '#c4b5fd',
                textMuted: '#5b21b6',
                border: '#2e1065',
            },
        },
    },
    rose: {
        id: 'rose',
        name: 'Gül',
        colors: {
            light: {
                background: '#fff1f2',
                surface: '#ffffff',
                surfaceLight: '#ffe4e6',
                primary: '#e11d48',
                primaryGradientFrom: '#e11d48',
                primaryGradientTo: '#db2777',
                accent: '#ec4899',
                textPrimary: '#4c0519',
                textSecondary: '#9f1239',
                textMuted: '#fda4af',
                border: '#fecdd3',
            },
            dark: {
                background: '#1a0810',
                surface: '#2d1018',
                surfaceLight: '#441524',
                primary: '#fb7185',
                primaryGradientFrom: '#f43f5e',
                primaryGradientTo: '#f472b6',
                accent: '#f472b6',
                textPrimary: '#ffe4e6',
                textSecondary: '#fda4af',
                textMuted: '#9f1239',
                border: '#4c0519',
            },
        },
    },
    monochrome: {
        id: 'monochrome',
        name: 'Sade',
        colors: {
            light: {
                background: '#f8fafc',
                surface: '#ffffff',
                surfaceLight: '#f1f5f9',
                primary: '#9333ea',
                primaryGradientFrom: '#9333ea',
                primaryGradientTo: '#db2777',
                accent: '#06b6d4',
                textPrimary: '#0f172a',
                textSecondary: '#475569',
                textMuted: '#94a3b8',
                border: '#e2e8f0',
            },
            dark: {
                background: '#0f172a',
                surface: '#1e293b',
                surfaceLight: '#334155',
                primary: '#a855f7',
                primaryGradientFrom: '#9333ea',
                primaryGradientTo: '#db2777',
                accent: '#22d3ee',
                textPrimary: '#f8fafc',
                textSecondary: '#94a3b8',
                textMuted: '#64748b',
                border: '#334155',
            },
        },
    },
    galaxy: {
        id: 'galaxy',
        name: 'Galaksi',
        colors: {
            light: {
                background: '#f8fafc',
                surface: '#ffffff',
                surfaceLight: '#f1f5f9',
                primary: '#4338ca',
                primaryGradientFrom: '#4338ca',
                primaryGradientTo: '#6366f1',
                accent: '#818cf8',
                textPrimary: '#1e1b4b',
                textSecondary: '#4338ca',
                textMuted: '#94a3b8',
                border: '#e2e8f0',
            },
            dark: {
                background: '#050505',
                surface: '#0d0d1a',
                surfaceLight: '#16162e',
                primary: '#818cf8',
                primaryGradientFrom: '#6366f1',
                primaryGradientTo: '#a78bfa',
                accent: '#c084fc',
                textPrimary: '#fafafa',
                textSecondary: '#94a3b8',
                textMuted: '#4338ca',
                border: '#1e1e3f',
            },
        },
    },
    sakura: {
        id: 'sakura',
        name: 'Sakura',
        colors: {
            light: {
                background: '#fff5f7',
                surface: '#ffffff',
                surfaceLight: '#ffe4e6',
                primary: '#ec4899',
                primaryGradientFrom: '#ec4899',
                primaryGradientTo: '#f472b6',
                accent: '#fb7185',
                textPrimary: '#831843',
                textSecondary: '#be185d',
                textMuted: '#fda4af',
                border: '#fecdd3',
            },
            dark: {
                background: '#1c0c11',
                surface: '#2d111a',
                surfaceLight: '#441829',
                primary: '#f472b6',
                primaryGradientFrom: '#f472b6',
                primaryGradientTo: '#fb7185',
                accent: '#f9a8d4',
                textPrimary: '#ffe4e6',
                textSecondary: '#fda4af',
                textMuted: '#9d174d',
                border: '#4c0519',
            },
        },
    },
    nord: {
        id: 'nord',
        name: 'Nord',
        colors: {
            light: {
                background: '#eceff4',
                surface: '#ffffff',
                surfaceLight: '#e5e9f0',
                primary: '#5e81ac',
                primaryGradientFrom: '#5e81ac',
                primaryGradientTo: '#81a1c1',
                accent: '#81a1c1',
                textPrimary: '#2e3440',
                textSecondary: '#4c566a',
                textMuted: '#d8dee9',
                border: '#d8dee9',
            },
            dark: {
                background: '#2e3440',
                surface: '#3b4252',
                surfaceLight: '#434c5e',
                primary: '#88c0d0',
                primaryGradientFrom: '#88c0d0',
                primaryGradientTo: '#81a1c1',
                accent: '#8fbcbb',
                textPrimary: '#eceff4',
                textSecondary: '#d8dee9',
                textMuted: '#4c566a',
                border: '#434c5e',
            },
        },
    },
    dracula: {
        id: 'dracula',
        name: 'Dracula',
        colors: {
            light: {
                background: '#fff5f5',
                surface: '#ffffff',
                surfaceLight: '#ffebeb',
                primary: '#990000',
                primaryGradientFrom: '#990000',
                primaryGradientTo: '#660000',
                accent: '#cc0000',
                textPrimary: '#1a0000',
                textSecondary: '#4d0000',
                textMuted: '#94a3b8',
                border: '#ffcccc',
            },
            dark: {
                background: '#0a0000',
                surface: '#1a0505',
                surfaceLight: '#2d0a0a',
                primary: '#ff0000',
                primaryGradientFrom: '#ff0000',
                primaryGradientTo: '#990000',
                accent: '#ff4d4d',
                textPrimary: '#ffffff',
                textSecondary: '#ffcccc',
                textMuted: '#6d0000',
                border: '#3d0000',
            },
        },
    },
    monokai: {
        id: 'monokai',
        name: 'Monokai',
        colors: {
            light: {
                background: '#f8f8f2',
                surface: '#ffffff',
                surfaceLight: '#f1f1f0',
                primary: '#a6e22e',
                primaryGradientFrom: '#a6e22e',
                primaryGradientTo: '#fd971f',
                accent: '#f92672',
                textPrimary: '#272822',
                textSecondary: '#49483e',
                textMuted: '#75715e',
                border: '#e6e6e6',
            },
            dark: {
                background: '#272822',
                surface: '#3e3d32',
                surfaceLight: '#49483e',
                primary: '#a6e22e',
                primaryGradientFrom: '#a6e22e',
                primaryGradientTo: '#fd971f',
                accent: '#66d9ef',
                textPrimary: '#f8f8f2',
                textSecondary: '#a6e22e',
                textMuted: '#75715e',
                border: '#49483e',
            },
        },
    },
    solarized: {
        id: 'solarized',
        name: 'Solarized',
        colors: {
            light: {
                background: '#fdf6e3',
                surface: '#eee8d5',
                surfaceLight: '#ddd6c1',
                primary: '#268bd2',
                primaryGradientFrom: '#268bd2',
                primaryGradientTo: '#2aa198',
                accent: '#b58900',
                textPrimary: '#073642',
                textSecondary: '#586e75',
                textMuted: '#93a1a1',
                border: '#eee8d5',
            },
            dark: {
                background: '#002b36',
                surface: '#073642',
                surfaceLight: '#268bd2',
                primary: '#268bd2',
                primaryGradientFrom: '#268bd2',
                primaryGradientTo: '#2aa198',
                accent: '#859900',
                textPrimary: '#93a1a1',
                textSecondary: '#839496',
                textMuted: '#586e75',
                border: '#073642',
            },
        },
    },
    matrix: {
        id: 'matrix',
        name: 'Matrix',
        colors: {
            light: {
                background: '#f0fff0',
                surface: '#ffffff',
                surfaceLight: '#e0ffe0',
                primary: '#008f11',
                primaryGradientFrom: '#008f11',
                primaryGradientTo: '#003b00',
                accent: '#00ff41',
                textPrimary: '#003b00',
                textSecondary: '#008f11',
                textMuted: '#00ff41',
                border: '#d0ffd0',
            },
            dark: {
                background: '#000000',
                surface: '#0d0d0d',
                surfaceLight: '#003b00',
                primary: '#00ff41',
                primaryGradientFrom: '#00ff41',
                primaryGradientTo: '#008f11',
                accent: '#003b00',
                textPrimary: '#00ff41',
                textSecondary: '#008f11',
                textMuted: '#003b00',
                border: '#0d0d0d',
            },
        },
    },
};

export const getTheme = async (): Promise<ThemeId> => {
    try {
        const themeId = await AsyncStorage.getItem('user_theme');
        const validThemes: ThemeId[] = ['classic', 'vintage', 'cinema', 'neon', 'ocean', 'forest', 'sunset', 'midnight', 'rose', 'monochrome', 'galaxy', 'sakura', 'nord', 'dracula', 'monokai', 'solarized', 'matrix'];
        return validThemes.includes(themeId as ThemeId) ? (themeId as ThemeId) : 'classic';
    } catch {
        return 'classic';
    }
};

export const setTheme = async (themeId: ThemeId): Promise<void> => {
    await AsyncStorage.setItem('user_theme', themeId);
};
